### ISSUE TITLE
 Blacklist too long game crash

### ISSUE THREAD

**Issue by erdos321** [L2jLiga/Loot-Bag-Mod-Fabric#16]
I put more than 400 items into the lootbagmod.json5,
when I want to start the game, the game crashed.
[crash-2023-12-19_21.48.51-client.txt](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/files/13716387/crash-2023-12-19_21.48.51-client.txt)

**Comment by L2jLiga** [comment]
As far as I see your crash is caused by invalid identifier used, I've added workaround to avoid crash in such case in [v4.0.1-1.20.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v4.0.1-1.20.2)
