### ISSUE TITLE
Hostile Mobs don't drop Bags

### ISSUE THREAD

**Issue by CheezBallzFTW** [L2jLiga/Loot-Bag-Mod-Fabric#2]
I set the config to drop bags from all hostile mobs, and I set the drop chance to 100. I killed like 50 zombies to be sure, but no bags dropped.

**Comment by L2jLiga** [comment]
Hi there!
Fix is available in [v1.0.2-1.19.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v1.0.2-1.19.2).

The only issue I noticed is for some reason lootbag is dropped twice from sheep and I have no idea 😅
