### ISSUE TITLE
Incompatibility with Inventorio

### ISSUE THREAD

**Issue by CheezBallzFTW** [L2jLiga/Loot-Bag-Mod-Fabric#4]
I don't know which mod can fix this so I will post an issue for Inventorio too. When using a loot bag from the utility belt (left hand) it doesn't leave the inventory. It makes infinite items.

**Comment by L2jLiga** [comment]
Fix released as [v1.0.4-1.19.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v1.0.4-1.19.2), will be available on ModRinth and CurseForge soon
