### ISSUE TITLE
Update to Inventorio Incompatibility

### ISSUE THREAD

**Issue by CheezBallzFTW** [L2jLiga/Loot-Bag-Mod-Fabric#5]
I can't comment on the previous issue but a fix could be a config option to make it drop the items on left click instead of right click. That'd help a lot for the multiplayer server I'm working on not being broken. Thanks :)

**Comment by L2jLiga** [comment]
Fix released as [v1.0.4-1.19.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v1.0.4-1.19.2), will be available on ModRinth and CurseForge soon
