### ISSUE TITLE
Drop Chance doesn't go below 100%

### ISSUE THREAD

**Issue by CheezBallzFTW** [L2jLiga/Loot-Bag-Mod-Fabric#6]
How do I make it drop with a 1% chance? I tried 1 but it came out as 100% and I tried 0.01 but it came out as 1000%

**Comment by L2jLiga** [comment]
Hey, this one is fixed in [v1.0.3-1.19.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v1.0.3-1.19.2)
