### ISSUE TITLE
Update 2 to Inventorio Incompatibility

### ISSUE THREAD

**Issue by CheezBallzFTW** [L2jLiga/Loot-Bag-Mod-Fabric#7]
The author of Inventorio said you could use the Inventorio api to add support since it has custom slots that aren't accounted for when removing the lootbag.

**Comment by L2jLiga** [comment]
Fix released as [v1.0.4-1.19.2](https://github.com/L2jLiga/Loot-Bag-Mod-Fabric/releases/tag/v1.0.4-1.19.2), will be available on ModRinth and CurseForge soon
